Revert "conf: Update kernel version to v4.19.325-cip123"
This reverts commit 7037b704201be195de020525a2e672fd48177363.

This is because the version update results in the following
compilation errors.

| /buildbot/build_daily_emlinux_am335xevmsk_latest_dev/build/build_am335x-evmsk_emlinux_core-image-weston/tmp-glibc/work-shared/am335x-evmsk/kernel-source/drivers/media/platform/omap3isp/ispccdc.c: In function 'ccdc_lsc_config':
| /buildbot/build_daily_emlinux_am335xevmsk_latest_dev/build/build_am335x-evmsk_emlinux_core-image-weston/tmp-glibc/work-shared/am335x-evmsk/kernel-source/drivers/media/platform/omap3isp/ispccdc.c:452:3: error: implicit declaration of function 'dma_sync_sgtable_for_cpu'; did you mean 'dma_sync_single_for_cpu'? [-Werror=implicit-function-declaration]
|    dma_sync_sgtable_for_cpu(isp->dev, &req->table.sgt,
|    ^~~~~~~~~~~~~~~~~~~~~~~~
|    dma_sync_single_for_cpu
|   CC [M]  drivers/media/rc/keymaps/rc-avermedia-a16d.o
| /buildbot/build_daily_emlinux_am335xevmsk_latest_dev/build/build_am335x-evmsk_emlinux_core-image-weston/tmp-glibc/work-shared/am335x-evmsk/kernel-source/drivers/media/platform/omap3isp/ispccdc.c:461:3: error: implicit declaration of function 'dma_sync_sgtable_for_device'; did you mean 'dma_sync_single_for_device'? [-Werror=implicit-function-declaration]
|    dma_sync_sgtable_for_device(isp->dev, &req->table.sgt,
|    ^~~~~~~~~~~~~~~~~~~~~~~~~~~
|    dma_sync_single_for_device