emlinux-image-compact: Restore apt.conf.d directory
This commit added a kind of workaround to fix following error in do_rootfs_finalize task.

ERROR: emlinux-image-compact-1.0-r0 do_rootfs_finalize:
ExecutionError('/home/build/work/build/tmp/work/emlinux-bookworm-amd64/emlinux-image-compact-qemu-amd64/1.0-r0/temp/run.do_rootfs_finalize.38826',
1, None, None)
ERROR: Logfile of failure stored in:
/home/build/work/build/tmp/work/emlinux-bookworm-amd64/emlinux-image-compact-qemu-amd64/1.0-r0/temp/log.do_rootfs_finalize.38826
Log data follows:
| DEBUG: Executing shell function do_rootfs_finalize
| find:
'/home/build/work/build/tmp/work/emlinux-bookworm-amd64/emlinux-image-compact-qemu-amd64/1.0-r0/rootfs/etc/apt/sources.list.d/':
No such file or directory
| WARNING: exit code 1 from a shell command.
ERROR: Task
(/home/build/work/build/../repos/meta-emlinux/recipes-core/images/emlinux-image-compact.bb:do_rootfs_finalize)
failed with exit code '1'
NOTE: Tasks Summary: Attempted 88 tasks of which 38 didn't need to be
rerun and 1 failed.

It seems as if do_rootfs_finalize task was updated by 1e33b12 ("image: Account for
differences with mmdebstrap") that causes above error.

Signed-off-by: Masami Ichikawa <masami.ichikawa@miraclelinux.com>