classes/dl-srcpkg: Fix task order problem
Since commit b0913306d94a ("Delay creation of initrd until end of rootfs
install") in isar, dl-srpkg and do_generate_initramfs tasks conflict their
mount/unmount process.
The result we got following error.

```
| DEBUG: Executing shell function rootfs_do_umounts
| umount: /home/build/work/build/tmp/work/emlinux-bookworm-amd64/emlinux-image-base-qemu-amd64/1.0-r0/rootfs/dev: target is busy.
| WARNING: exit code 32 from a shell command.
| DEBUG: Python function do_generate_initramfs finished
ERROR: Task (/home/build/work/build/../repos/meta-emlinux/recipes-core/images/emlinux-image-base.bb:do_generate_initramfs) failed with exit code '1'
NOTE: Tasks Summary: Attempted 140 tasks of which 0 didn't need to be rerun and 1 failed.
WARNING: /home/build/work/build/tmp/work/emlinux-bookworm-amd64/emlinux-image-base-qemu-amd64/1.0-r0/rootfs/sys/firmware left mounted, unmounting...
WARNING: /home/build/work/build/tmp/work/emlinux-bookworm-amd64/emlinux-image-base-qemu-amd64/1.0-r0/rootfs/sys left mounted, unmounting...
WARNING: /home/build/work/build/tmp/work/emlinux-bookworm-amd64/emlinux-image-base-qemu-amd64/1.0-r0/rootfs/proc left mounted, unmounting...
WARNING: /home/build/work/build/tmp/work/emlinux-bookworm-amd64/emlinux-image-base-qemu-amd64/1.0-r0/rootfs/dev left mounted, unmounting...

Summary: 1 task failed:
  /home/build/work/build/../repos/meta-emlinux/recipes-core/images/emlinux-image-base.bb:do_generate_initramfs
Summary: There were 4 WARNING messages.
Summary: There was 1 ERROR message, returning a non-zero exit code.
```

To fix the issue, we should put dl-srcpkg's task into right place.
It looks as if running dl-srcpkg task after do_generate_initramfs and before
do_rootfs_finalize is better place.

Signed-off-by: Masami Ichikawa <masami.ichikawa@miraclelinux.com>