scripts: Add more recipes to BBMASK
When run "bitbake world", there is some build errors.

Added epiphany_3.30.3.b and packagegroup-self-hosted.bb to avoid
following error.

ERROR: Nothing PROVIDES 'webkitgtk' (but
/home/masami/emlinux/truly-latest/build-emlinux/../repos/poky/meta/recipes-gnome/epiphany/epiphany_3.30.3.bb
DEPENDS on or otherwise requires it)
ERROR: Required build target 'meta-world-pkgdata' has no buildable
providers.
Missing or unbuildable dependency chain was: ['meta-world-pkgdata',
'epiphany', 'webkitgtk']

Added linux-firmware-rpidistro_git.bb to avoid following error.

ERROR: linux-firmware-rpidistro-20190114-1+rpt10-r0 do_fetch: Fetcher
failure: Unable to find revision
b66ab26cebff689d0d3257f56912b9bb03c20567 in branch master even from
upstream
ERROR: linux-firmware-rpidistro-20190114-1+rpt10-r0 do_fetch: Fetcher
failure for URL: 'git://github.com/RPi-Distro/firmware-nonfree'. Unable
to fetch URL from any source.
ERROR: linux-firmware-rpidistro-20190114-1+rpt10-r0 do_fetch:
ERROR: linux-firmware-rpidistro-20190114-1+rpt10-r0 do_fetch: Function
failed: base_do_fetch
ERROR: Logfile of failure stored in:
/home/masami/emlinux/truly-latest/build/tmp-glibc/work/all-emlinux-linux/linux-firmware-rpidistro/20190114-1+rpt10-r0/temp/log.do_fetch.32384
ERROR: Task
(/home/masami/emlinux/truly-latest/build/../repos/meta-emlinux/recipes-kernel/linux-firmware-rpidistro/linux-firmware-rpidistro_git.bb:do_fetch)
failed with exit code '1'

Signed-off-by: Masami Ichikawa <masami.ichikawa@miraclelinux.com>