scripts: Fix cve-check if package is installed from different debian version
Fixed an issue that caused an error when a package was installed from a
different debian version than the DISTRO.

This commit fixes following error.

2025-08-04 06:54:25,212:INFO: Checking CVEs ...
Traceback (most recent call last):
  File "/home/build/work/repos/meta-emlinux/scripts/cve_check.py", line
721, in <module>
    main(parse_options())
  File "/home/build/work/repos/meta-emlinux/scripts/cve_check.py", line
674, in main
    cves = create_cves_info(db_file, debian_cve_list,
uniq_installed_pkgs, installed_pkgs, args.debian_codename, cve_products,
linux_kernel_src_dir, cip_kernel_sec_dir, kev_list)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/build/work/repos/meta-emlinux/scripts/cve_check.py", line
508, in create_cves_info
    cves = merge_cve_data(uniq_installed_pkgs,
installed_pkgs_cves_by_debian_data, cve_not_in_debian,
installed_pkgs_cves_by_nvd_data, codename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/build/work/repos/meta-emlinux/scripts/cve_check.py", line
210, in merge_cve_data
    cveinfo[pkgname] = create_debian_pkg_cve_info(pkgname, bin_pkgname,
installed_version, debian_cveinfo, nvd_cveinfo, codename)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/build/work/repos/meta-emlinux/scripts/cve_check.py", line
160, in create_debian_pkg_cve_info
    dc = debian_cveinfo[cveid]["releases"][codename]
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
KeyError: 'bookworm'

Signed-off-by: Masami Ichikawa <masami.ichikawa@miraclelinux.com>