busybox: Add PN to PACKAGES
Since Isar upstream commit 20ba7ee2
("dpkg: let do_deploy_deb runtime depend on do_deploy_source"),
a runtime dependency on busybox via RPROVIDES cannot be resolved as below.

ERROR: Nothing RPROVIDES 'busybox'
NOTE: Runtime target 'busybox' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['busybox']
ERROR: Required build target 'emlinux-image-compact' has no buildable providers.
Missing or unbuildable dependency chain was: ['emlinux-image-compact', 'busybox', 'busybox']

When PACKAGES is specified in a recipe, its list of package names is set
to RPROVIDES. Unlike Yocto, the Isar implementation makes the default
value of PACKAGES empty, so this recipe provides the package name for
resolving runtime dependencies as busybox-syslogd only. As a result,
it fails due to a name mismatch when looking up the default package name.

To avoid this failure, this change also provides PN as a package name
to resolve runtime dependencies.